version: "3.9"

services:

  # redis:
  #   container_name: redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 60 1 --loglevel warning

  app:
    build: 
      context: .
      args:
        - DEV=true
    container_name: app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    # depends_on:
    #   - redis

  # worker:
  #   build: .
  #   command: celery -A core worker -l INFO
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - redis
  #     - app
  
  # beatworker:
  #   build: .
  #   command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - redis
  #     - app
  #     - worker