version: "3.9"

services:

  # redis:
  #   container_name: redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 60 1 --loglevel warning

  app:
    build: 
      context: .
      args:
        - DEV=true
    container_name: app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - dev-static-data:/vol/web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:

  # worker:
  #   build: .
  #   command: celery -A core worker -l INFO
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - redis
  #     - app
  
  # beatworker:
  #   build: .
  #   command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - redis
  #     - app
  #     - worker