---
name: Django Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker Compose
      run: docker-compose up -d
    - name: Run All Test
      run: docker-compose run --rm app sh -c "python manage.py test"
    - name : Lint
      run : docker-compose run --rm app sh -c "flake8"